### ISSUE TITLE
Methods missing / split from AdvertisementWatcher

### ISSUE THREAD

**Issue by ansoni-san** [saltosystems/winrt-go#66]
Hi,

It seems that `AllowExtendedAdvertisements` is needed for bluetooth behaviour that a user would find typical.

Docs Ref: https://learn.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.advertisement.bluetoothleadvertisementwatcher?view=winrt-22621

Is there a reason why this gets split into `iBluetoothLEAdvertisementWatcher2`? I can't find a way to access this setting.

I am currently trying to get the Windows behaviour of https://github.com/tinygo-org/bluetooth on-par with Linux and Darwin, and from what I have read setting `AllowExtendedAdvertisements` to true is likely to be necessary.

**Comment by jagobagascon** [comment]
Hi!

If I remember correctly Microsoft uses private interfaces to define the methods and properties of the runtime classes. We just read those interfaces and generate the code accordingly.

The reason there are several interfaces per class is (I guess) because when a new field or method is added, Microsoft just creates a new private interface instead of modifying the existing one. This is transparent to the end user so it's not a big deal.

 The `BluetoothLEAdvertisementWatcher` class methods are specified in the `iBluetoothLEAdvertisementWatcher` and  `iBluetoothLEAdvertisementWatcher2` interfaces. Other classes like [BluetoothLEDevice](https://learn.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.bluetoothledevice?view=winrt-22621) have up to [5 private interfaces](https://github.com/saltosystems/winrt-go/blob/93887f96e59ff7c4423379652847f4121beb071b/windows/devices/bluetooth/bluetoothledevice.go#L251) ([here's an older IDL where only 4 of them existed](https://github.com/tpn/winsdk-10/blob/9b69fd26ac0c7d0b83d378dba01080e93349c2ed/Include/10.0.16299.0/winrt/windows.devices.bluetooth.idl#L157)).

**The reason that property is not accessible to you is because we did not generate it**. We used an allowlist to only generate a subset of classes and methods and we never needed that property. Read the README for more information on why we do this.

Hope this clarifies your doubts.

That being said I added a PR that includes the property you need: https://github.com/saltosystems/winrt-go/pull/67

**Comment by ansoni-san** [comment]
Thank you so much for the thorough response. Yes I imagined it was because of the way they were described in the winmd file.

Thanks a lot for the pull request as well. It has shown me how the project works as a benefit to me. 

Cheers 🙂👍
