### ISSUE TITLE
Static Function Name Collisions

### ISSUE THREAD

**Issue by nickajacks1** [saltosystems/winrt-go#85]
I was looking to potentially add support for Bluetooth Classic devices and came across a function name collision.

To reproduce:

`go run github.com/saltosystems/winrt-go/cmd/winrt-go-gen -debug -class Windows.Devices.Bluetooth.BluetoothDevice -method-filter Close -method-filter FromBluetoothAddressAsync`

This will create `func FromBluetoothAddressAsync(address uint64) (*foundation.IAsyncOperation, error)` in `windows/devices/bluetooth/bluetoothdevice.go`, which conflicts with the existing function declaration in bluetoothledevice.go.

The only non-breaking way to fix this that I could think of would be to add some kind of method-remap option so that you can rename static methods.  Otherwise, you may need to further subdivide classes into their own packages or add a prefix to static function names by default.

Ref: 
https://learn.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.bluetoothdevice.frombluetoothaddressasync?view=winrt-22621
https://learn.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.bluetoothledevice.frombluetoothaddressasync?view=winrt-22621

**Comment by jagobagascon** [comment]
This is something that's automatically addressed in non-static methods, but we completely missed the static ones. Thank you for letting us know.

Considering this repo does not include any versioning tags I'm not really happy with making a breaking change. But I think the way to go is to prefix the static methods with their class name.

Instead of a method-remap option we could just keep both versions for those methods and mark the old one as deprecated. 
```go
// FromBluetoothAddressWithBluetoothAddressTypeAsync is kept for backwards compatibility purposes
// and will be removed in the future.
// See https://github.com/saltosystems/winrt-go/issues/85 for more info.
//
// Deprecated: use BluetoothLEDeviceFromBluetoothAddressWithBluetoothAddressTypeAsync instead.
var FromBluetoothAddressWithBluetoothAddressTypeAsync = BluetoothLEDeviceFromBluetoothAddressWithBluetoothAddressTypeAsync

func BluetoothLEDeviceFromBluetoothAddressWithBluetoothAddressTypeAsync(bluetoothAddress uint64, bluetoothAddressType BluetoothAddressType) (*foundation.IAsyncOperation, error) {
    //...
}
```

Currently there are only 6 static methods, so this could be hardcoded in the code until it gets removed.
